FROM ruby:2.7.8
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    nodejs \
    postgresql-client \
    yarn
WORKDIR /product-register
COPY Gemfile Gemfile.lock /product-register/
RUN bundle install
COPY . .
ENV RAILS_ENV=production
ENV DISABLE_DATABASE_ENVIRONMENT_CHECK=1

# アセットを本番用にプリコンパイル
RUN bundle exec rails assets:precompile

CMD ["bash", "-c", "bundle exec rails db:migrate && bundle exec rails s -e production -b 0.0.0.0"]